### ISSUE TITLE
Unable to create certificate using ingress annotations - MalformedCSRException: CSR must mark the SAN extension critical when it has an empty subject

### ISSUE THREAD

**Issue by pault28** [jniebuhr/aws-pca-issuer#6]
```
Kubernetes: 1.19 (v1.19.6-eks-49a6c0)
aws-pca-issuer: Helm release 0.1.0
certmanager: 1.3.1
```

I have a working setup of this addon but currently unable to use it to auto-generate certificate using annotations such as below:
```
apiVersion: extensions/v1beta1
# apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: myprivate-ca
  name: podinfo
  namespace: podinfo
spec:
  rules:
  - host: podinfo.infrastructure.com
    http:
      paths:
      - path: /
        backend:
          serviceName: podinfo
          servicePort: 80
  tls:
    - hosts:
      - podinfo.infrastructure.com
      secretName: podinfo10
```

Creating certificate using the CRD works, e.g with:
```
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: podinfo-cert
  namespace: podinfo
spec:
  commonName: podinfo.infrastructure.com
  dnsNames:
    - podinfo.infrastructure.com
  issuerRef:
    group: awspca.cert-manager.io
    kind: AWSPCAClusterIssuer
    name: myprivate-ca
  renewBefore: 360h0m0s
  secretName: podinfo-cert
```

The error I get when using the ingress approach to autogenerate the certificate is:
```
2021-04-28T18:42:12.883939412Z {"level":"error","ts":1619635332.883713,"logger":"controllers.CertificateRequest","msg":"failed to request certificate from PCA","certificaterequest":"podinfo/podinfo3-rxrmp","error":"MalformedCSRException: CSR must mark the SAN extension critical when it has an empty subject.","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\ngithub.com/jniebuhr/aws-pca-issuer/pkg/controllers.(*CertificateRequestReconciler).Reconcile\n\t/workspace/pkg/controllers/certificaterequest_controller.go:171\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99"}
```

The approach of using ingress works with other issuers as we currently use vault issuer but we want to migrate to AWS ACM.
Does this work for anyone?

**Comment by jniebuhr** [comment]
Hi,
I haven't actually tested this before. Can you post both of the CertificateRequest CRs that are created?
I can probably check why it's not working from there.

**Comment by pault28** [comment]
Not sure I know exactly what to post whilst keeping sensitive information off. It is easy to test it as documented here https://cert-manager.io/docs/usage/ingress/#how-it-works

**Comment by jniebuhr** [comment]
I'll have to try and reproduce it later this week then.

**Comment by pault28** [comment]
@jniebuhr - any chance you got round to looking at this?

**Comment by pault28** [comment]
Turns out that this is resolvable by doing below:
```
apiVersion: extensions/v1beta1
# apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: myprivate-ca
    cert-manager.io/issuer-kind: AWSPCAClusterIssuer
    cert-manager.io/issuer-group: awspca.cert-manager.io
    cert-manager.io/common-name: podinfo.infrastructure.com
  name: podinfo
  namespace: podinfo
spec:
  rules:
  - host: podinfo.infrastructure.com
    http:
      paths:
      - path: /
        backend:
          serviceName: podinfo
          servicePort: 80
  tls:
    - hosts:
      - podinfo.infrastructure.com
      secretName: podinfo10
```
Main change being adding the extra annotation `cert-manager.io/common-name: podinfo.infrastructure.com`
Happy for this to be closed perhaps with an example of generating cert this way.
